import 'models/nutrition.dart';

/// Offline starter food list (per stated serving), including Filipino staples.
/// Same data as the Expo app's foods.ts.
const List<Food> kFoods = [
  Food(id: 'rice-white', name: 'White rice, cooked', serving: '1 cup (158g)', calories: 205, protein: 4, carbs: 45, fat: 0),
  Food(id: 'rice-brown', name: 'Brown rice, cooked', serving: '1 cup (195g)', calories: 218, protein: 5, carbs: 46, fat: 2),
  Food(id: 'oats', name: 'Oatmeal, cooked', serving: '1 cup (234g)', calories: 154, protein: 6, carbs: 27, fat: 3),
  Food(id: 'bread-white', name: 'White bread', serving: '1 slice (28g)', calories: 75, protein: 3, carbs: 14, fat: 1),
  Food(id: 'bread-wheat', name: 'Whole wheat bread', serving: '1 slice (32g)', calories: 82, protein: 4, carbs: 14, fat: 1),
  Food(id: 'pandesal', name: 'Pandesal', serving: '1 piece (33g)', calories: 98, protein: 3, carbs: 18, fat: 2),
  Food(id: 'pasta', name: 'Pasta, cooked', serving: '1 cup (140g)', calories: 220, protein: 8, carbs: 43, fat: 1),
  Food(id: 'potato', name: 'Potato, baked', serving: '1 medium (173g)', calories: 161, protein: 4, carbs: 37, fat: 0),
  Food(id: 'sweet-potato', name: 'Sweet potato (kamote)', serving: '1 medium (130g)', calories: 112, protein: 2, carbs: 26, fat: 0),
  Food(id: 'chicken-breast', name: 'Chicken breast, grilled', serving: '100g', calories: 165, protein: 31, carbs: 0, fat: 4),
  Food(id: 'chicken-thigh', name: 'Chicken thigh, roasted', serving: '100g', calories: 209, protein: 26, carbs: 0, fat: 11),
  Food(id: 'pork-belly', name: 'Pork belly (liempo), grilled', serving: '100g', calories: 366, protein: 20, carbs: 0, fat: 31),
  Food(id: 'samgyupsal', name: 'Samgyupsal (grilled pork belly)', serving: '100g', calories: 370, protein: 20, carbs: 2, fat: 31),
  Food(id: 'chicken-wings-korean', name: 'Korean chicken wings, glazed', serving: '100g', calories: 250, protein: 19, carbs: 10, fat: 15),
  Food(id: 'kimchi', name: 'Kimchi', serving: '100g', calories: 30, protein: 2, carbs: 6, fat: 0),
  Food(id: 'cheese-corn', name: 'Cheese corn', serving: '100g', calories: 170, protein: 5, carbs: 20, fat: 8),
  Food(id: 'pork-chop', name: 'Pork chop, lean', serving: '100g', calories: 231, protein: 26, carbs: 0, fat: 14),
  Food(id: 'beef-ground', name: 'Ground beef, 85% lean', serving: '100g', calories: 250, protein: 26, carbs: 0, fat: 15),
  Food(id: 'beef-sirloin', name: 'Beef sirloin, grilled', serving: '100g', calories: 206, protein: 30, carbs: 0, fat: 9),
  Food(id: 'bangus', name: 'Bangus (milkfish), grilled', serving: '100g', calories: 162, protein: 21, carbs: 0, fat: 8),
  Food(id: 'tilapia', name: 'Tilapia, grilled', serving: '100g', calories: 128, protein: 26, carbs: 0, fat: 3),
  Food(id: 'salmon', name: 'Salmon, baked', serving: '100g', calories: 208, protein: 20, carbs: 0, fat: 13),
  Food(id: 'tuna-can', name: 'Tuna, canned in water', serving: '1 can (142g)', calories: 128, protein: 29, carbs: 0, fat: 1),
  Food(id: 'shrimp', name: 'Shrimp, cooked', serving: '100g', calories: 99, protein: 24, carbs: 0, fat: 0),
  Food(id: 'egg', name: 'Egg, large', serving: '1 egg (50g)', calories: 72, protein: 6, carbs: 0, fat: 5),
  Food(id: 'tofu', name: 'Tofu, firm', serving: '100g', calories: 144, protein: 17, carbs: 3, fat: 9),
  Food(id: 'tocino', name: 'Tocino', serving: '100g', calories: 265, protein: 15, carbs: 18, fat: 14),
  Food(id: 'longganisa', name: 'Longganisa', serving: '2 pieces (80g)', calories: 260, protein: 13, carbs: 6, fat: 20),
  Food(id: 'adobo-chicken', name: 'Chicken adobo', serving: '1 cup (240g)', calories: 372, protein: 30, carbs: 8, fat: 24),
  Food(id: 'sinigang-pork', name: 'Pork sinigang', serving: '1 bowl (350g)', calories: 290, protein: 22, carbs: 12, fat: 18),
  Food(id: 'tinola', name: 'Chicken tinola', serving: '1 bowl (350g)', calories: 215, protein: 24, carbs: 9, fat: 9),
  Food(id: 'sisig', name: 'Pork sisig', serving: '1 serving (150g)', calories: 410, protein: 22, carbs: 5, fat: 34),
  Food(id: 'lumpia', name: 'Lumpiang shanghai', serving: '3 pieces (75g)', calories: 220, protein: 8, carbs: 16, fat: 14),
  Food(id: 'pancit', name: 'Pancit canton', serving: '1 cup (220g)', calories: 320, protein: 12, carbs: 45, fat: 10),
  Food(id: 'broccoli', name: 'Broccoli, steamed', serving: '1 cup (156g)', calories: 55, protein: 4, carbs: 11, fat: 1),
  Food(id: 'spinach', name: 'Spinach, raw', serving: '1 cup (30g)', calories: 7, protein: 1, carbs: 1, fat: 0),
  Food(id: 'mixed-veg', name: 'Mixed vegetables, cooked', serving: '1 cup (160g)', calories: 118, protein: 5, carbs: 24, fat: 1),
  Food(id: 'banana', name: 'Banana', serving: '1 medium (118g)', calories: 105, protein: 1, carbs: 27, fat: 0),
  Food(id: 'apple', name: 'Apple', serving: '1 medium (182g)', calories: 95, protein: 0, carbs: 25, fat: 0),
  Food(id: 'mango', name: 'Mango', serving: '1 medium (200g)', calories: 135, protein: 2, carbs: 35, fat: 1),
  Food(id: 'avocado', name: 'Avocado', serving: '1/2 fruit (100g)', calories: 160, protein: 2, carbs: 9, fat: 15),
  Food(id: 'milk', name: 'Milk, whole', serving: '1 cup (244g)', calories: 149, protein: 8, carbs: 12, fat: 8),
  Food(id: 'milk-skim', name: 'Milk, skim', serving: '1 cup (245g)', calories: 83, protein: 8, carbs: 12, fat: 0),
  Food(id: 'yogurt-greek', name: 'Greek yogurt, plain', serving: '170g cup', calories: 100, protein: 17, carbs: 6, fat: 1),
  Food(id: 'cheese-cheddar', name: 'Cheddar cheese', serving: '1 slice (28g)', calories: 113, protein: 7, carbs: 0, fat: 9),
  Food(id: 'coffee-black', name: 'Coffee, black', serving: '1 cup (240ml)', calories: 2, protein: 0, carbs: 0, fat: 0),
  Food(id: 'coffee-latte', name: 'Café latte', serving: '1 grande (473ml)', calories: 190, protein: 13, carbs: 19, fat: 7),
  Food(id: 'soda', name: 'Soft drink, regular', serving: '1 can (330ml)', calories: 139, protein: 0, carbs: 35, fat: 0),
  Food(id: 'beer', name: 'Beer', serving: '1 bottle (330ml)', calories: 142, protein: 1, carbs: 11, fat: 0),
  Food(id: 'whey', name: 'Whey protein shake', serving: '1 scoop (30g)', calories: 120, protein: 24, carbs: 3, fat: 1),
  Food(id: 'peanut-butter', name: 'Peanut butter', serving: '2 tbsp (32g)', calories: 188, protein: 8, carbs: 6, fat: 16),
  Food(id: 'almonds', name: 'Almonds', serving: '28g (23 nuts)', calories: 164, protein: 6, carbs: 6, fat: 14),
  Food(id: 'chips', name: 'Potato chips', serving: '28g bag', calories: 152, protein: 2, carbs: 15, fat: 10),
  Food(id: 'chocolate', name: 'Milk chocolate bar', serving: '1 bar (45g)', calories: 235, protein: 3, carbs: 26, fat: 13),
  Food(id: 'ice-cream', name: 'Ice cream, vanilla', serving: '1/2 cup (66g)', calories: 137, protein: 2, carbs: 16, fat: 7),
  Food(id: 'burger', name: 'Cheeseburger, fast food', serving: '1 burger (120g)', calories: 303, protein: 15, carbs: 33, fat: 13),
  Food(id: 'fries', name: 'French fries', serving: 'medium (117g)', calories: 365, protein: 4, carbs: 48, fat: 17),
  Food(id: 'pizza', name: 'Pizza, cheese', serving: '1 slice (107g)', calories: 285, protein: 12, carbs: 36, fat: 10),
  Food(id: 'fried-chicken', name: 'Fried chicken, 1 piece', serving: '1 piece (140g)', calories: 380, protein: 28, carbs: 12, fat: 24),

  // --- Filipino dishes -------------------------------------------------------
  // Curated estimates for common local dishes, per stated serving. Grounded in
  // public-domain USDA ingredient values and typical recipes; nutrition facts
  // aren't copyrightable, so these are free to bundle. Treat as estimates —
  // real portions and recipes vary. For authoritative figures, see FNRI PhilFCT.
  Food(id: 'adobo-pork', name: 'Pork adobo', serving: '1 cup (240g)', calories: 400, protein: 26, carbs: 8, fat: 29),
  Food(id: 'kare-kare', name: 'Kare-kare (oxtail, peanut sauce)', serving: '1 serving (250g)', calories: 352, protein: 20, carbs: 14, fat: 24),
  Food(id: 'kaldereta', name: 'Beef kaldereta', serving: '1 cup (240g)', calories: 378, protein: 24, carbs: 12, fat: 26),
  Food(id: 'menudo', name: 'Pork menudo', serving: '1 cup (240g)', calories: 315, protein: 22, carbs: 16, fat: 18),
  Food(id: 'afritada', name: 'Chicken afritada', serving: '1 cup (240g)', calories: 300, protein: 24, carbs: 15, fat: 15),
  Food(id: 'mechado', name: 'Beef mechado', serving: '1 cup (240g)', calories: 350, protein: 24, carbs: 12, fat: 22),
  Food(id: 'bistek', name: 'Bistek tagalog', serving: '1 serving (200g)', calories: 280, protein: 26, carbs: 8, fat: 16),
  Food(id: 'bicol-express', name: 'Bicol express', serving: '1 serving (150g)', calories: 390, protein: 14, carbs: 10, fat: 33),
  Food(id: 'laing', name: 'Laing (taro leaves in coconut)', serving: '1 serving (150g)', calories: 222, protein: 5, carbs: 10, fat: 18),
  Food(id: 'dinuguan', name: 'Dinuguan', serving: '1 cup (240g)', calories: 318, protein: 22, carbs: 8, fat: 22),
  Food(id: 'pinakbet', name: 'Pinakbet', serving: '1 cup (200g)', calories: 185, protein: 8, carbs: 18, fat: 9),
  Food(id: 'chopsuey', name: 'Chopsuey', serving: '1 cup (200g)', calories: 159, protein: 9, carbs: 15, fat: 7),
  Food(id: 'ginisang-monggo', name: 'Ginisang monggo (mung bean stew)', serving: '1 cup (240g)', calories: 190, protein: 14, carbs: 22, fat: 5),
  Food(id: 'tortang-talong', name: 'Tortang talong (eggplant omelet)', serving: '1 piece (120g)', calories: 199, protein: 10, carbs: 6, fat: 15),
  Food(id: 'chicken-curry-ph', name: 'Chicken curry (Filipino)', serving: '1 cup (240g)', calories: 290, protein: 24, carbs: 12, fat: 16),
  Food(id: 'lechon-kawali', name: 'Lechon kawali', serving: '100g', calories: 449, protein: 20, carbs: 0, fat: 41),
  Food(id: 'lechon', name: 'Lechon (roast pig)', serving: '100g', calories: 394, protein: 22, carbs: 0, fat: 34),
  Food(id: 'crispy-pata', name: 'Crispy pata', serving: '100g', calories: 475, protein: 22, carbs: 0, fat: 43),
  Food(id: 'daing-bangus', name: 'Daing na bangus, fried', serving: '100g', calories: 250, protein: 22, carbs: 0, fat: 18),
  Food(id: 'bulalo', name: 'Bulalo (beef shank soup)', serving: '1 bowl (350g)', calories: 299, protein: 24, carbs: 8, fat: 19),
  Food(id: 'nilagang-baka', name: 'Nilagang baka', serving: '1 bowl (350g)', calories: 275, protein: 24, carbs: 10, fat: 15),
  Food(id: 'arroz-caldo', name: 'Arroz caldo', serving: '1 bowl (300g)', calories: 255, protein: 14, carbs: 34, fat: 7),
  Food(id: 'goto', name: 'Goto (rice porridge with tripe)', serving: '1 bowl (300g)', calories: 245, protein: 15, carbs: 30, fat: 7),
  Food(id: 'champorado', name: 'Champorado', serving: '1 bowl (250g)', calories: 257, protein: 5, carbs: 48, fat: 5),
  Food(id: 'batchoy', name: 'La Paz batchoy', serving: '1 bowl (350g)', calories: 349, protein: 20, carbs: 38, fat: 13),
  Food(id: 'beef-tapa', name: 'Beef tapa', serving: '100g', calories: 246, protein: 24, carbs: 6, fat: 14),
  Food(id: 'sinangag', name: 'Sinangag (garlic fried rice)', serving: '1 cup (180g)', calories: 237, protein: 4, carbs: 44, fat: 5),
  Food(id: 'pancit-bihon', name: 'Pancit bihon', serving: '1 cup (200g)', calories: 280, protein: 10, carbs: 42, fat: 8),
  Food(id: 'pancit-malabon', name: 'Pancit malabon', serving: '1 serving (250g)', calories: 381, protein: 18, carbs: 48, fat: 13),
  Food(id: 'spaghetti-ph', name: 'Filipino-style spaghetti', serving: '1 cup (250g)', calories: 328, protein: 14, carbs: 50, fat: 8),
  Food(id: 'sotanghon', name: 'Sotanghon guisado', serving: '1 cup (200g)', calories: 246, protein: 10, carbs: 38, fat: 6),
  Food(id: 'kwek-kwek', name: 'Kwek-kwek (3 pcs)', serving: '3 pieces (90g)', calories: 195, protein: 8, carbs: 16, fat: 11),
  Food(id: 'fishball', name: 'Fishball (5 pcs)', serving: '5 pieces (75g)', calories: 125, protein: 6, carbs: 14, fat: 5),
  Food(id: 'isaw', name: 'Isaw (chicken, 1 stick)', serving: '1 stick (40g)', calories: 98, protein: 9, carbs: 2, fat: 6),
  Food(id: 'banana-cue', name: 'Banana cue (1 stick)', serving: '1 stick (120g)', calories: 206, protein: 1, carbs: 46, fat: 2),
  Food(id: 'turon', name: 'Turon (1 piece)', serving: '1 piece (80g)', calories: 214, protein: 2, carbs: 38, fat: 6),
  Food(id: 'siomai', name: 'Siomai (3 pcs)', serving: '3 pieces (90g)', calories: 177, protein: 10, carbs: 14, fat: 9),
  Food(id: 'siopao', name: 'Siopao asado (1 pc)', serving: '1 piece (120g)', calories: 221, protein: 10, carbs: 34, fat: 5),
  Food(id: 'halo-halo', name: 'Halo-halo', serving: '1 serving (300g)', calories: 334, protein: 6, carbs: 64, fat: 6),
  Food(id: 'leche-flan', name: 'Leche flan', serving: '1 slice (100g)', calories: 300, protein: 8, carbs: 40, fat: 12),
  Food(id: 'bibingka', name: 'Bibingka', serving: '1 piece (100g)', calories: 257, protein: 6, carbs: 38, fat: 9),
  Food(id: 'puto', name: 'Puto (1 pc)', serving: '1 piece (40g)', calories: 89, protein: 2, carbs: 18, fat: 1),
  Food(id: 'biko', name: 'Biko (sticky rice cake)', serving: '1 slice (100g)', calories: 266, protein: 3, carbs: 50, fat: 6),
  Food(id: 'taho', name: 'Taho', serving: '1 cup (250g)', calories: 146, protein: 6, carbs: 26, fat: 2),
  Food(id: 'ube-halaya', name: 'Ube halaya', serving: '1 serving (100g)', calories: 202, protein: 3, carbs: 34, fat: 6),
  Food(id: 'sago-gulaman', name: "Sago't gulaman", serving: '1 glass (350ml)', calories: 164, protein: 1, carbs: 40, fat: 0),
];
